def set_description(key: str):
    description = {
        "SU-59 - Login Erro": "Erro durante o processo de login",
        "SU-60 - Alteração de senha de Usuário": "Alteração da senha de um usuário no sistema",
        "SU-61 - Atualização de dados do Usuário": "Atualização das informações cadastrais de um usuário",
        "SU-63 - Autorização de Acesso": "Concessão de permissões de acesso a determinado recurso",
        "SU-64 - Login Criação": "Criação de uma conta de usuário e senha",
        "SU-30 - Zimbra DeskTop": "Configuração e suporte para o cliente de email Zimbra Desktop",
        "SU-31 - Mozilla ThunderBird": "Configuração e suporte para o cliente de email Mozilla Thunderbird",
        "SU-32 - Outlook": "Configuração e suporte para o cliente de email Microsoft Outlook",
        "IMP-10 - Impressora - Hardware - Manutenção Corretiva": "Manutenção corretiva do hardware de uma impressora",
        "IMP-11 - Impressora - Hardware - Manutenção Preventiva": "Manutenção preventiva do hardware de uma impressora",
        "PC-09 - Periféricos - HD Externo": "Instalação e suporte para HD externo",
        "PC-17 - Backups": "Configuração e suporte para backups de dados",
        "PC-18 - Periférico - Microfone": "Instalação e suporte para microfone como periférico",
        "SU-04 - Computador - Instalação": "Instalação do sistema operacional e programas em um computador",
        "SU-05 - Computador - Manutenção": "Manutenção periódica de um computador",
        "SU-06 - Computador - Substituição": "Substituição de hardware ou software em um computador",
        "SU-07 - Computador - Formatação": "Formatação e reinstalação do sistema operacional em um computador",
        "SU-08 - Computador - Remanejamento / Movimentação": "Movimentação física de um computador",
        "SU-09 - Periféricos - Mouse": "Instalação e suporte para mouse como periférico",
        "SU-10 - Periféricos - Teclado": "Instalação e suporte para teclado como periférico",
        "SU-16 - Periféricos - Nobreak": "Instalação e suporte para nobreak",
        "SU-25 - Ponto de Rede - Crimpagem de ponto": "Crimpagem de cabo de rede",
        "SU-26 - Ponto de Rede - Remanejamento de Ponto": "Movimentação física de ponto de rede",
        "SU-27 - Ponto de Rede - Instalação de Cabeamento Cat 5": "Instalação de cabeamento de rede categoria 5",
        "SU-34 - Impressora - Manutenção": "Manutenção de impressoras",
        "SU-35 - Impressora - Troca de Tonner / Suprimentos": "Troca de toner ou suprimentos de impressoras",
        "SU-39 - Impressora - Erro": "Identificação e resolução de erros em impressoras",
        "SU-52 - Monitor - Hardware - Remanejamento / Movimentação": "Movimentação física de monitor",
        "IT-02 - Erro de acesso a página": "Identificação e resolução de erros de acesso a páginas da web",
        "SU-22 - Sem acesso": "Usuário sem acesso aos recursos necessários",
        "SU-03 - Microsoft Windows 10": "Suporte e manutenção para o sistema operacional Microsoft Windows 10",
        "Su-11 - Windows Adicionar Computador no Domínio": "Adição de computador ao domínio do Windows",
        "SU-12 - Windows Compartilhamento de Pasta": "Configuração de compartilhamento de pastas no Windows",
        "SU-13 - Windows Formatação": "Formatação e reinstalação do sistema operacional Windows",
        "SU-14 - Windows Instalação": "Instalação do sistema operacional Windows",
        "SU-15 - Windows Manutenção": "Manutenção periódica do sistema operacional Windows",
        "SF-26 - GlobalProtect": "Configuração e suporte para o serviço de VPN GlobalProtect",
        "SU-70 - Antivirus": "Instalação e suporte para software antivírus",
        "SU-72 - FreePDF": "Suporte para a utilização do software FreePDF",
        "SU-73 - Microsoft Office": "Instalação e suporte para o pacote de aplicativos Microsoft Office",
        "SU-75 - Google Chrome": "Instalação e suporte para o navegador Google Chrome",
        "SU-76 - Mozilla FireFox": "Instalação e suporte para o navegador Mozilla Firefox",
        "SU-78 - 7-Zip": "Instalação e suporte para o software de compactação 7-Zip",
        "SU-79 - Java": "Instalação e suporte para a plataforma Java",
        "SU-80 - Java Runtime Environment": "Instalação e suporte para o ambiente de execução Java",
        "SU-81 - Adobe Acrobat": "Instalação e suporte para o software Adobe Acrobat",
        "SU-85 - Pje - Instalação": "Instalação e suporte para o sistema PJe",
        "SU-86 - Pje - Erro": "Identificação e resolução de erros no sistema PJe",
        "SU-89 - Módulo de Segurança Bancário": "Instalação e suporte para módulo de segurança bancário",
        "SU-90 - Arcgis": "Instalação e suporte para o software ArcGIS",
        "SU-92 - Siafi": "Suporte para o sistema SIAFI",
        "SU-66 - VOIP - Configuração": "Configuração e suporte para serviços de VOIP"
    }

    return description[key]