def set_description(key: str):
    description = {
        "SU-59 - Login Erro": "Identificação e resolução de problemas durante o processo de login no sistema.",
        "SU-60 - Alteração de senha de Usuário": "Alteração segura da senha de um usuário no sistema, garantindo conformidade com políticas de segurança.",
        "SU-61 - Atualização de dados do Usuário": "Atualização e revisão de informações cadastrais de usuários, incluindo dados pessoais e corporativos.",
        "SU-63 - Autorização de Acesso": "Concessão e gerenciamento de permissões de acesso a recursos específicos, seguindo normas internas.",
        "SU-64 - Login Criação": "Processo de criação de credenciais de acesso para novos usuários, incluindo definição de privilégios.",
        "SU-30 - Zimbra DeskTop": "Configuração, instalação e suporte para o cliente de email Zimbra Desktop.",
        "SU-31 - Mozilla ThunderBird": "Configuração, instalação e suporte técnico para o cliente de email Mozilla Thunderbird.",
        "SU-32 - Outlook": "Configuração avançada e suporte para o cliente de email Microsoft Outlook.",
        "IMP-10 - Impressora - Hardware - Manutenção Corretiva": "Execução de manutenção corretiva em hardware de impressoras para restaurar funcionalidades.",
        "IMP-11 - Impressora - Hardware - Manutenção Preventiva": "Realização de manutenção preventiva em impressoras para evitar falhas e prolongar a vida útil.",
        "PC-09 - Periféricos - HD Externo": "Configuração, instalação e suporte técnico para dispositivos de armazenamento externos.",
        "PC-17 - Backups": "Planejamento, configuração e suporte para rotinas de backup de dados críticos.",
        "PC-18 - Periférico - Microfone": "Instalação e suporte técnico para microfones utilizados como periféricos.",
        "SU-04 - Computador - Instalação": "Configuração inicial de computadores, incluindo instalação de sistema operacional e softwares necessários.",
        "SU-05 - Computador - Manutenção": "Manutenção periódica de computadores para otimização de desempenho e detecção de problemas.",
        "SU-06 - Computador - Substituição": "Substituição ou atualização de hardware e software em computadores.",
        "SU-07 - Computador - Formatação": "Formatação de discos e reinstalação completa do sistema operacional e aplicativos.",
        "SU-08 - Computador - Remanejamento / Movimentação": "Realocação física de computadores, com verificação de conectividade e funcionalidade pós-movimentação.",
        "SU-09 - Periféricos - Mouse": "Configuração e suporte técnico para o uso de mouses como dispositivos de entrada.",
        "SU-10 - Periféricos - Teclado": "Configuração e suporte técnico para teclados, incluindo dispositivos ergonômicos ou especializados.",
        "SU-16 - Periféricos - Nobreak": "Instalação e suporte para dispositivos nobreak, garantindo proteção contra quedas de energia.",
        "SU-25 - Ponto de Rede - Crimpagem de ponto": "Execução de crimpagem em cabos de rede para ativação de pontos físicos.",
        "SU-26 - Ponto de Rede - Remanejamento de Ponto": "Movimentação e reconfiguração de pontos de rede, conforme novas necessidades estruturais.",
        "SU-27 - Ponto de Rede - Instalação de Cabeamento Cat 5": "Instalação e organização de cabeamento de rede categoria 5 para novas estações.",
        "SU-34 - Impressora - Manutenção": "Manutenção geral de impressoras para correção de falhas e otimização de desempenho.",
        "SU-35 - Impressora - Troca de Tonner / Suprimentos": "Substituição de toner ou outros suprimentos em impressoras para garantir a continuidade de operações.",
        "SU-39 - Impressora - Erro": "Diagnóstico e solução de erros relacionados ao funcionamento de impressoras.",
        "SU-52 - Monitor - Hardware - Remanejamento / Movimentação": "Movimentação e realocação física de monitores, com ajustes necessários.",
        "IT-02 - Erro de acesso a página": "Diagnóstico e resolução de problemas de acesso a páginas da web.",
        "SU-22 - Sem acesso": "Análise e solução para usuários sem acesso aos recursos ou sistemas necessários.",
        "SU-03 - Microsoft Windows 10": "Suporte técnico completo para o sistema operacional Microsoft Windows 10.",
        "SU-11 - Windows Adicionar Computador no Domínio": "Configuração para adicionar computadores ao domínio da rede Windows.",
        "SU-12 - Windows Compartilhamento de Pasta": "Configuração de pastas compartilhadas no Windows para acesso controlado.",
        "SU-13 - Windows Formatação": "Formatação e reinstalação do sistema operacional Windows, preservando conformidade com padrões.",
        "SU-14 - Windows Instalação": "Instalação completa do sistema operacional Windows em novos equipamentos.",
        "SU-15 - Windows Manutenção": "Manutenção preventiva e corretiva do sistema operacional Windows.",
        "SF-26 - GlobalProtect": "Configuração e suporte para o serviço de VPN GlobalProtect.",
        "SU-70 - Antivirus": "Instalação e suporte para soluções antivírus, garantindo segurança dos sistemas.",
        "SU-72 - FreePDF": "Instalação e suporte para o software de criação e edição de PDFs FreePDF.",
        "SU-73 - Microsoft Office": "Instalação e suporte técnico para o pacote de produtividade Microsoft Office.",
        "SU-75 - Google Chrome": "Instalação e suporte para o navegador de internet Google Chrome.",
        "SU-76 - Mozilla FireFox": "Instalação e suporte para o navegador Mozilla Firefox.",
        "SU-78 - 7-Zip": "Instalação e suporte técnico para o software de compactação 7-Zip.",
        "SU-79 - Java": "Instalação e suporte técnico para a plataforma de desenvolvimento Java.",
        "SU-80 - Java Runtime Environment": "Instalação e suporte técnico para o ambiente de execução Java Runtime Environment.",
        "SU-81 - Adobe Acrobat": "Instalação e suporte técnico para o software Adobe Acrobat para leitura e edição de PDFs.",
        "SU-85 - Pje - Instalação": "Instalação e configuração do sistema PJe para acesso e uso adequados.",
        "SU-86 - Pje - Erro": "Diagnóstico e correção de falhas ou erros no sistema PJe.",
        "SU-89 - Módulo de Segurança Bancário": "Instalação e suporte para módulos de segurança bancários, garantindo transações seguras.",
        "SU-90 - Arcgis": "Instalação e suporte técnico para o software de mapeamento e análise ArcGIS.",
        "SU-92 - Siafi": "Suporte técnico completo para o sistema de administração financeira SIAFI.",
        "SU-66 - VOIP - Configuração": "Configuração e suporte técnico para serviços de telefonia VOIP.",
    }

    return description.get(key, "Descrição não encontrada")
